png("plot3.png", width=480, height=480)
source("load.R")
times <- strptime(paste(newdf$Date,  newdf$Time, " "), "%d/%m/%Y %H:%M:%S")
plot(times, newdf$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(times,newdf$Sub_metering_2, col="red")
lines(times,newdf$Sub_metering_3, col="blue")
legend("topright", lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
